### ISSUE TITLE
New 'rade reminders

### ISSUE THREAD

**Issue by bigdatadave** [michael-robbins/emojirades-plusplus#10]
Implement a method of sending reminders to be sent between games if a new 'rade has not been posted yet. We need two types of reminders:
- to the previous 'rader if they have not sent a new phrase to the winner yet
- to the winner if they have been sent a phrase but not posted a 'rade yet

So this might combine with #7 and #8 as we need to know the players involved and the current state of the game. If we use the method of sending new 'rades via the bot this should be easier, otherwise we'll need a command (@bot sent) or something so players can notify the bot/channel. How to detect a new 'rade starting is trickier, might just need to be on the next post by the winner after a 'rade has been sent.

Might also be useful to allow players to trigger reminders manually via command.

**Comment by michael-robbins** [comment]
Maybe for the manual notification we add a '@bot status' where it prints out the current game state.

Examples:
"Status: @michael was the previous winner, @phelios is currently emojirading and everyone else is guessing"
"Status: @michael was the last winner, @phelios has the emojirade but hasn't posted yet and everyone else is waiting!"
"Status: @michael was the last winner, @phelios is waiting for him to send the emojirade and everyone else is getting impatient!"

**Comment by michael-robbins** [comment]
If the bot is maintaining who's won/etc, then having the previous winner send the emojirade to the bot instead, which will save it, then relay that through to the correct guesser sounds like the easiest thing.

**Comment by michael-robbins** [comment]
You can even have the bot ping the user telling them that someone was the winner and they need to reply with the new 'rade.

"@michael-robbins: @phelios correctly guessed the word! Please reply to this with the next 'rade!"

**Comment by michael-robbins** [comment]
Some of this has been implemented currently (bot pinging on a win/etc), but we don't have and reoccurring notifications, as we can only react to people typing in the chat (and an event being fired).

Maybe just each time someone does an '@bot status' style command, pinging all the relevant parties will be enough!

**Comment by michael-robbins** [comment]
I've merged in the game progression code, that will ping all relevant parties as the game progresses through its various states.

Also there is a 'game status' command now that will print out the old/current winners which will be a nice reminder to whoever is currently providing the emojirade

Is this current functionality enough @bigdatadave @phelios ? Or were we wanting to provide some sort of automated/cron style alerting that slowly backs off in duration?

**Comment by bigdatadave** [comment]
I was initially thinking automated, but this might be enough for now. Other active players will always police the game anyway, and peer pressure works better than automated reminders :)

**Comment by michael-robbins** [comment]
Good enough for me! Cheers!
