### ISSUE TITLE
Rewrite how configuration files are handled

### ISSUE THREAD

**Issue by michael-robbins** [michael-robbins/emojirades-plusplus#11]
Currently scorekeeper has its own way of maintaining a configuration file across local/S3.

I'd like to make this generic and able to be reused for other parts of the program (mainly the new game state functionality).

Break out the logic into a generic 'ConfigurationHandler' and provide generic ways of CRUD a 'file'. Think about how the current scorekeeper will use this along with the new game state class.

**Comment by michael-robbins** [comment]
Branch: configuration-handler

**Comment by michael-robbins** [comment]
This has been completed now, the handling of the underlying bytes object is abstracted away from the system that needs a config file, it handles both local files and S3 objects.

It expects the wrapping class to provide a bytes object that is written/read when required.

**Comment by phelios** [comment]
I see some syntax errors and missing classes. Assuming this has not been tested? 🤔
