### ISSUE TITLE
On success guess, bot should show the raw 'rade to the channel

### ISSUE THREAD

**Issue by michael-robbins** [michael-robbins/emojirades-plusplus#111]
It's currently showing the sanitized 'rade, which is slightly confusing.

Ensure any display of the 'rade is the raw one, but internally the sanitized one is used.

**Comment by bigdatadave** [comment]
I was thinking about this, and the only problem is that we'd then be working with unsanitized user input. Not sure how Slack deals with bot messages but this could lead to a Bobby Tables situation. So then we'd need a kind of half-sanitized "display" version of the rade that has anything potentially nasty stripped out but not anything else?

**Comment by michael-robbins** [comment]
When the bot prints out untrusted user input, it's always wrapped in backticks, which forces the slack clients to ignore all formatting and print the raw text. So users shouldn't be able to force other slack clients to render emojis/etc.

**Comment by michael-robbins** [comment]
having said that, if the user puts in backticks... that might break it... so I'll remove them before printing!
