### ISSUE TITLE
Help text should show how to provide alternatives when giving a 'rade

### ISSUE THREAD

**Issue by bigdatadave** [michael-robbins/emojirades-plusplus#123]
☝️

**Comment by michael-robbins** [comment]
I'm pretty sure each command is allowed to provide multiple different help text lines, so this should be pretty straight forward!

**Comment by michael-robbins** [comment]
I've updated the existing command to include an alternatives example.

https://github.com/michael-robbins/emojirades-plusplus/blob/master/plusplusbot/command/gamestate_commands/set_emojirade_command.py#L14

We could overhaul the examples to provide an (example, description) of each example command...

**Comment by michael-robbins** [comment]
Thoughts?

**Comment by bigdatadave** [comment]
Yeah I think providing a short description and example would be better. It wouldn't be obvious to a newbie player what "emojirade foo | bar" means or how it differs from "emojirade foo".
