### ISSUE TITLE
Don't look at emoji text when determining an inferred win

### ISSUE THREAD

**Issue by michael-robbins** [michael-robbins/emojirades-plusplus#41]
Currently if the emojirade is 'pie' and someone posts 'foo :pie: bar', the bot will award the win.

In the above case it should not award the win, as :pie: is resolved to an emoji client side.

**Comment by michael-robbins** [comment]
@phelios what's your thoughts on this?

**Comment by phelios** [comment]
hmm.. I think it's alright though. It rarely happens for 'rades to have a direct emoji equivalent words in it. Even if it does, I think it's clever to use emoji to describe the answer.

**Comment by michael-robbins** [comment]
Yep I agree, closing!
