### ISSUE TITLE
Allow old winner to easily change who the new winner is

### ISSUE THREAD

**Issue by bigdatadave** [michael-robbins/emojirades-plusplus#46]
In some cases, a guesser will guess the 'rade correctly (or correctly enough), however it won't be an exact string match for the 'rade provided so the bot doesn't automatically award the points. Unless the old winner is on the ball and awards points manually, this allows another user to :ninja: the points by guessing the exact string match and having the bot award them the points.

A game admin could currently fix this by manually doing a -- for the ninja, a ++ for the ninja'd party and then starting a new game with the correct users. However, it would be good if the old winner could fix this with a single command and without needing admin rights.

Maybe something like:
@emojirades fixwinner <@real winner>

This would -- the new winner, ++ the real winner provided and then set new winner to real winner. This should only be available to the old winner (or admins), and only possible while the game is in the guessed/won state before a new 'rade is sent. The old winner could then provide a new rade like normal which be sent to the real winner and the game moves on.

**Comment by michael-robbins** [comment]
Created branch issue-46 to track this.
