### ISSUE TITLE
Handle quote characters

### ISSUE THREAD

**Issue by phelios** [michael-robbins/emojirades-plusplus#52]
Emojirades transforms quotes into a different type of quote, so it won't match if a 'rade has a quote/double quote in it.

**Comment by michael-robbins** [comment]
Proposed solution is just to strip out quotes in comparing the result, as well as when performing the emojirade comparison check.

This will ensure no invalid/utf-8/magical other chars make it in.

Either that or we do some sanitizing where we replace all types of quotes with a single type/codepoint.

/shrug
