### ISSUE TITLE
Alternative acceptable answers

### ISSUE THREAD

**Issue by phelios** [michael-robbins/emojirades-plusplus#53]
Often a 'rade can be expressed in a different ways but still correct. For example, acronyms or different spellings.

Would it be a good idea to have a list of 'rade to match with per round?

example:
`emojirade PUBG | PlayerUnknowns' Battlegrounds`

**Comment by michael-robbins** [comment]
Yep this is fine, as long as we can't really see the separator char aka '|' being actually used in a 'rade, which I can't really think of.....

**Comment by michael-robbins** [comment]
OK the approach here is we'll split the emojirade text on '|' and then treat the emojirade as a list from now on.

All comparisons check that the guess is 'in' the emojirade list vs a direct equality check.
