### ISSUE TITLE
Next 'rades registry

### ISSUE THREAD

**Issue by phelios** [michael-robbins/emojirades-plusplus#7]
Allow a user to send another user a new emojirade to be guessed by other.

Requirements:
- Only the winner can use this feature
- It need to be hidden from other users, nfi how it will work
- store the emojirade so that it can be used to winner detection later on.

**Comment by phelios** [comment]
Maybe we can do this through private message to the bot user.
- The previous winner sends a PM to bot user with the next clue
- Bot check the winner registry, making sure the user is the previous winner
- Bot then send the 'rade to the new winner through PM.

**Comment by michael-robbins** [comment]
Yep, given we're saving state in S3, we can maybe just have a game state object that's mirrored into S3 as well, like the scores file, that keeps track of the winner/previous winner/current rade/etc

**Comment by michael-robbins** [comment]
If we decide to start doing more than 2 things in S3 might be worth rewriting parts of the S3/file flushing logic to handle it better, I don't think my approach was the nicest way to do it...

**Comment by michael-robbins** [comment]
Branch game-state is tracking saving the current game's state and making that available to processes!

**Comment by michael-robbins** [comment]
Blocked on #11

**Comment by michael-robbins** [comment]
Configfile rewrite has been done and released. so we're clear to get the game state stuff going now

**Comment by michael-robbins** [comment]
I've left a stub in the new gamestate file, it would be just fill it out like the scorekeeper class and do whatever's needed to record gamestate.

**Comment by michael-robbins** [comment]
Game state has mostly been written, just finishing testing now.

**Comment by michael-robbins** [comment]
This has now been implemented!
