### ISSUE TITLE
FixWinner glitches

### ISSUE THREAD

**Issue by phelios** [michael-robbins/emojirades-plusplus#84]
- Apparently the previous winner can fixwinner @self and they'll get the point for it
- fixwinner can be done after new rade is sent, which is kinda weird.
  - and the state is not updated/reset.

**Comment by michael-robbins** [comment]
Created a new status check called 'only_not_in_progress' and enforced it on the fixwinner command.

Updated logic in fixwinner to reject old_winner and winner targets, given they don't make sense!

**Comment by michael-robbins** [comment]
So now fixwinner can only be used if the gamestate is in new_game or waiting, once an emojirade is posted the command doesn't work.

Along with the other checks around not being the old_winner or winner, this should cover the cases outlined.
