### ISSUE TITLE
Self-destruct timer

### ISSUE THREAD

**Issue by phelios** [michael-robbins/emojirades-plusplus#95]
If emojirade is inactive for 24 hours, reset everything.
- Exceptions during holiday periods

**Comment by michael-robbins** [comment]
This will require timers in the bot as well, which isn't there. So that'll have to be a new concept.

**Comment by bigdatadave** [comment]
👎 let the game run at its own pace. Admins can step in if a player goes truly AWOL.

**Comment by phelios** [comment]
Spring cleaning:
- closing this due to lack of interest.
